### ISSUE TITLE
使用更高效、更准确的insightface模型教程

### ISSUE THREAD

**Issue by dev-fox-101** [MT-Photos/mt-photos-deepface#16]
[kqstone](https://github.com/kqstone) 大佬已经集成了insightface的模型
https://github.com/kqstone/mt-photos-insightface-unofficial

insightface是开源中准确率最高的预训练模型，特别是针对亚洲人脸型，比官方仓库使用的Facenet512准确率高很多
可以大幅改善识别完成后，一个人物被识别为多个人物的情况；

### Docker容器运行

- 下载镜像

```
docker pull kqstone/mt-photos-insightface-unofficial:latest
```

- 创建及运行容器

```
docker run -i -p 8066:8066 -e API_AUTH_KEY=mt_photos_ai_extra --name mt-photos-insightface-unofficial --restart="unless-stopped" kqstone/mt-photos-insightface-unofficial:latest
```

## docker-compose模板
```yaml
version: "3"

services:
  mtphotos:
    image: registry.cn-hangzhou.aliyuncs.com/mtphotos/mt-photos:latest
    container_name: mtphotos
    restart: always
    ports:
      - 8063:8063
    volumes:
      - /volume1/docker/mt_photos/config:/config
      - /volume1/photos/mt_photos_upload:/upload
      - /volume1/xxx/其他需要映射的目录:/photos
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
    dns:
      - 114.114.114.114
    depends_on:
      - mtphotos_ai
      - mtphotos_face_api
  mtphotos_ai:
    image: registry.cn-hangzhou.aliyuncs.com/mtphotos/mt-photos-ai:onnx-latest
    container_name: mtphotos_ai
    restart: always
    ports:
      - 8060:8000
    environment:
      - API_AUTH_KEY=mt_photos_ai_extra
  mtphotos_face_api:
    image: registry.cn-hangzhou.aliyuncs.com/vito0101/mt-photos-insightface-unofficial:latest
    container_name: mtphotos_face_api
    restart: always
    ports:
      - 8066:8066
    environment:
      - API_AUTH_KEY=mt_photos_ai_extra

```

###  API配置参数  

**人脸置信度阈值设置** 建议填 0.65
**人脸匹配差异度阈值** 建议填 0.5

![image](https://github.com/user-attachments/assets/cac22ed8-0ab3-4ade-a0e9-3a41631cb72f)

##  无法下载镜像

以下2个镜像已内置 buffalo_l 模型

可以使用这个国内的地址拉取镜像
```
docker pull registry.cn-hangzhou.aliyuncs.com/vito0101/mt-photos-insightface-unofficial:latest

docker tag registry.cn-hangzhou.aliyuncs.com/vito0101/mt-photos-insightface-unofficial:latest  kqstone/mt-photos-insightface-unofficial:latest
```

第1条命令为拉取镜像
第2条命令为将镜像标记为Docker hub源，这样可以在图形化创建容器时使用

#### armV8版本镜像
```bash
docker pull registry.cn-hangzhou.aliyuncs.com/vito0101/mt-photos-insightface-unofficial:arm-latest

docker tag registry.cn-hangzhou.aliyuncs.com/vito0101/mt-photos-insightface-unofficial:arm-latest  kqstone/mt-photos-insightface-unofficial:arm-latest

# 启动容器
docker run -i -p 8066:8066 -e API_AUTH_KEY=mt_photos_ai_extra --name mt-photos-insightface-unofficial --restart="unless-stopped" kqstone/mt-photos-insightface-unofficial:arm-latest
```

#### 启动容器后，测试api提示不是人脸识别API

第一次启动容器后需要下载模型，如果由于网络问题，下载失败，可以按下面的方法手动下载镜像

1、创建容器时，要映射  /root/.insightface/models 这个目录

    不能直接映射/root   不能直接映射/root  不能直接映射/root

2、将模型文件 buffalo_l.zip 解压到映射的目录中；
模型文件下载地址：https://github.com/kqstone/mt-photos-insightface-unofficial/releases/tag/models
或者百度网盘：https://pan.baidu.com/s/1SsY7_2t7aORh2jCvGWtD1A?pwd=1234

比如目录映射为：  -v /mnt/docker/insightface/models:/root/.insightface/models
需要把buffalo_l.zip的文件解压到/mnt/docker/insightface/models/buffalo_l

解压完成后，在 /mnt/docker/insightface/models/buffalo_l 下面可以看到 1k3d68.onnx、2d106det.onnx、det_10g.onnx、genderage.onnx、w600k_r50.onnx 5个文件

![目录结构](https://github.com/user-attachments/assets/f2136a3e-499a-4a9c-9870-3fd68f7108d1)

创建容器的完整命令：
```bash
docker run -i -p 8066:8066 -e API_AUTH_KEY=mt_photos_ai_extra -v /mnt/docker/insightface/models:/root/.insightface/models --name mt-photos-insightface-unofficial --restart="unless-stopped" kqstone/mt-photos-insightface-unofficial:latest
```

![创建容器](https://github.com/user-attachments/assets/684cd404-9687-4bdb-843b-271cb1170020)

###  Windows如何使用

参考官方Windows版本的pyinstaller打包，我将kqstone/mt-photos-insightface-unofficial仓库的代码打包为Windows可以直接运行的exe文件

下载附件中的 mt-photos-insightface-unofficial-exe.zip 压缩包，解压后查看内部的 使用说明.txt 

##  API配置参数  

人脸置信度阈值设置 建议填 0.65
人脸匹配差异度阈值 建议填 0.5

![image](https://github.com/user-attachments/assets/cac22ed8-0ab3-4ade-a0e9-3a41631cb72f)

## Windows版本及模型下载

百度网盘：

https://pan.baidu.com/s/1SsY7_2t7aORh2jCvGWtD1A?pwd=1234
